### PR TITLE
Allow reference node url from outside of bundle

### PR DESCRIPTION
**Pull request by miles-au**
Hey! I was just working on a project that downloads models from a server, made it a little easier if I could reach files from outside the Bundle.main

### CODE REVIEW

**Comment by olexale** [comment]
Hi @miles-au ! Thanks again for your contribution!

I have a proposition: instead of a flag, let's just check if the `referenceUrl` is not nil, and if it is — fallback to the proposed approach. 

In that case, we keep the API simpler for our users.

Kind regards,
Oleksandr

**Comment by miles-au** [comment]
@olexale I've made some changes to the code, will you please give it a look over?

**Comment by olexale** [comment]
Thanks @miles-au !

**Comment by mpowloka** [comment]
Hello @OleksiiShvachenko! Do you know when this change will be released? :)

**Comment by mehranshoqi** [comment]
Hello @miles-au !

**Pull request merged**
