### PR TITLE
Images can load from Flutter assets

### PR DESCRIPTION
**Pull request by Topazoo**
Images to be used by geometries can now be stored in the Flutter application in addition to the default location(directly in Runner).

_GeometryBuilder.getMaterialProperty()_ will check the default location for the provided file. If it is not found, **/assets/images/** will be checked.

Detailed Changelog:

Added _registrar_ property directly to the _ArkitPlugin_ for access to bundle files (with associated setter and getter).
Set the _registrar_ property in _ArkitPlugin.registerWithRegistrar()_.
Added fallback logic to _GeometryBuilder.getMaterialProperty()_ that uses the registrar to check Flutter assets stored in **/assets/images/**.

### CODE REVIEW

**Comment by Topazoo** [comment]
P.S. Thanks for making this awesome plugin!!!

**Comment by olexale** [comment]
Hi @Topazoo,
Thanks for this contribution!

**Comment by olexale** [comment]
The only one thing I think we may change is that with the current implementation we force users to use `/assets/images`.

Will it be fine to require a full path, like instead of `earth.jpg` which should be located in `/assets/images`, user will provide `/assets/images/earth.jpg`? 

In that case we will get rid of magical path `/assets/images` and allow flexibility for `/assets/img/earth.jpg`-like solutions.

What do you think?

Thanks!

**Comment by Topazoo** [comment]
Hey @olexale!

Yeah requiring a full path to Flutter assets is a great call. You’re right that it adds a lot more flexibility.

I’ll update the code very soon!

**Pull request merged**
