### PR TITLE
Added Pivot

### LINKED ISSUE #76: [Question] Where is the pivot property?
Just curious, on the SCNNode object there is a pivot property, I don't see that exposed in ARKit. I'm sure I must be missing something basic.

I'm trying to rotate text around its centerpoint and (evidently) to do that I need to access the pivot property.

Many thanks for the great package! I'm having so much fun working with AR!

### PR DESCRIPTION
**Pull request by Rohithgilla12**
Closes #76 

Hey, @olexale please check this and let me know if I need to make any other changes.

### CODE REVIEW

**Comment by olexale** [comment]
Hey @Rohithgilla12 ,

Could you please make sure that the proposed changes really make the pivot property work? The most basic usage sample would fit. Thanks in advance!

Kind regards,
Oleksandr

**Comment by Rohithgilla12** [comment]
Hey how do I test that? 
I'm not understanding how to test😅

**Comment by olexale** [comment]
Hi! Read about the property you've added, find a real-world use case, implement this use case (I recommend starting with any of plugin's sample). Hope that helps 🙂

**Comment by Rohithgilla12** [comment]
Sure I'll give it a try.

**Comment by olexale** [comment]
This request looks abandoned so I'm closing it. Feel free to re-open it when you finish the implementation.

**Pull request closed without merging**
